"use client";

import { ChangeEvent, ReactNode, useEffect, useLayoutEffect, useMemo, useRef, useState } from "react";
import { getCatalogProject, getProjectVariant, getVerifiedProjectLiveUrl, projectCatalog } from "@/lib/catalog";
import { createDefaultResume } from "@/lib/defaults";
import { clearDraft, loadDraft, saveDraft } from "@/lib/storage";
import { accentOptions, bulletStyles, fontOptions, formatDate, makeId, migrateResumeDocument, parseLegacyDate, resumeTypes, sectionKeys, type BulletItem, type ContactLink, type DateRange, type ResumeDocument, type ResumeProject, type ResumeType, type SectionKey } from "@/lib/schema";

const labels: Record<ResumeType, string> = { legal: "Legal data / legal technology", finance: "Finance data", healthcare: "Healthcare data", enterprise: "Enterprise / cross-industry data", general: "General AI/data" };
const sectionLabels: Record<SectionKey, string> = { summary: "Summary", experience: "Professional Experience", projects: "Relevant Projects", skills: "Technical Skills", education: "Education", certifications: "Certifications" };
const clone = (value: ResumeDocument) => structuredClone(value);
const download = (name: string, content: string) => { const url = URL.createObjectURL(new Blob([content], { type: "application/json" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url); };
const move = <T,>(items: T[], from: number, to: number) => { const next = [...items]; const [item] = next.splice(from, 1); next.splice(to, 0, item); return next; };

type Fit = "comfortable" | "compact" | "two-page" | "overflow";

export default function Home() {
  const initial = useMemo(() => typeof window === "undefined" ? { document: createDefaultResume(), recovered: false } : loadDraft(), []);
  const [resume, setResume] = useState<ResumeDocument>(initial.document ?? createDefaultResume());
  const [history, setHistory] = useState<ResumeDocument[]>([]);
  const [future, setFuture] = useState<ResumeDocument[]>([]);
  const [saveState, setSaveState] = useState<"saved" | "saving" | "unsaved">(initial.document ? "saved" : "unsaved");
  const [notice, setNotice] = useState(initial.recovered ? "A saved draft could not be recovered. A fresh default is open." : "");
  const [fit, setFit] = useState<Fit>("comfortable");
  const fileRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    const timer = window.setTimeout(() => { saveDraft(resume); setSaveState("saved"); }, 350);
    return () => window.clearTimeout(timer);
  }, [resume]);

  const commit = (next: ResumeDocument) => { setHistory((items) => [...items.slice(-49), clone(resume)]); setFuture([]); setResume(next); setFit("comfortable"); setSaveState("saving"); };
  const update = (change: (draft: ResumeDocument) => void) => { const next = clone(resume); change(next); commit(next); };
  const undo = () => { const previous = history.at(-1); if (!previous) return; setFuture((items) => [clone(resume), ...items]); setHistory((items) => items.slice(0, -1)); setResume(previous); setFit("comfortable"); setSaveState("saving"); };
  const redo = () => { const next = future[0]; if (!next) return; setHistory((items) => [...items, clone(resume)]); setFuture((items) => items.slice(1)); setResume(next); setFit("comfortable"); setSaveState("saving"); };
  const addProject = (slug: string) => update((draft) => {
    if (draft.projects.some((project) => project.catalogSlug === slug)) return;
    const project = getCatalogProject(slug); const variant = getProjectVariant(slug, draft.resumeType);
    if (!project || !variant) return;
    draft.projects.push({ id: makeId(), catalogSlug: slug, title: project.title, technologies: variant.technologyOrder ? [...variant.technologyOrder, ...project.technologies.filter((item) => !variant.technologyOrder!.includes(item))] : [...project.technologies], bullets: variant.bullets.map((bullet) => ({ id: makeId(), text: bullet.text })) });
  });
  const importFile = (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]; if (!file) return;
    file.text().then((text) => {
      try {
        const result = migrateResumeDocument(JSON.parse(text));
        if (!result.ok) { setNotice(result.error); return; }
        if (confirm("Replace the current draft with this imported resume?")) { commit(result.value); setNotice("Imported, migrated if needed, and saved locally."); }
      } catch { setNotice("That file is not valid JSON."); }
    });
    event.target.value = "";
  };
  const fitLabel = fit === "comfortable" ? "1 page" : fit === "compact" ? "1 page · compact" : fit === "two-page" ? "2 pages" : "1-page limit exceeded";
  const selectedCount = resume.projects.length;

  return <main className="app-shell">
    <header className="app-header no-print"><div><p className="eyebrow">VAIBHAV KHURANA</p><h1>Resume studio</h1><p>ATS-safe, editable, and print-ready.</p></div><p className={`save-state ${saveState}`} aria-live="polite">{saveState === "saving" ? "Saving locally…" : saveState === "unsaved" ? "Unsaved changes" : "Saved locally"}</p></header>
    <nav className="toolbar no-print" aria-label="Resume actions">
      <label className="toolbar-select"><span>Resume type</span><select value={resume.resumeType} onChange={(event) => update((draft) => { draft.resumeType = event.target.value as ResumeType; })}>{resumeTypes.map((type) => <option key={type} value={type}>{labels[type]}</option>)}</select></label>
      <button className="primary" onClick={() => { if (confirm("Replace this draft with the selected type's default resume?")) commit(createDefaultResume(resume.resumeType)); }}>Start from default</button>
      <span className="toolbar-divider" />
      <button onClick={undo} disabled={!history.length}>Undo</button><button onClick={redo} disabled={!future.length}>Redo</button>
      <span className="toolbar-divider" />
      <button onClick={() => download("vaibhav-khurana-resume-v2.json", JSON.stringify(resume, null, 2))}>Download JSON</button><button onClick={() => fileRef.current?.click()}>Import JSON</button><input ref={fileRef} className="visually-hidden" type="file" accept="application/json" onChange={importFile} />
      <button className="quiet-danger" onClick={() => { if (confirm("Clear the local V2 draft? This cannot be undone.")) { clearDraft(); setResume(createDefaultResume(resume.resumeType)); setHistory([]); setFuture([]); setNotice("Local draft cleared. A fresh default is open."); } }}>Clear draft</button>
      <button className="primary print-button" onClick={() => window.print()}>Print / Save PDF</button>
    </nav>
    {notice && <p className="notice no-print" role="status">{notice}<button aria-label="Dismiss message" onClick={() => setNotice("")}>×</button></p>}
    <div className="workspace">
      <aside className="editor no-print" aria-label="Resume editor">
        <section className="editor-intro"><span>Editable document</span><strong>{selectedCount} project{selectedCount === 1 ? "" : "s"} selected</strong></section>
        <Panel title="Profile" open><Field label="Name" value={resume.profile.name} onChange={(value) => update((draft) => { draft.profile.name = value; })} /><Field label="Headline (optional)" value={resume.profile.headline} onChange={(value) => update((draft) => { draft.profile.headline = value; })} /><div className="field-grid"><Field label="Location" value={resume.profile.location} onChange={(value) => update((draft) => { draft.profile.location = value; })} /><Field label="Phone" value={resume.profile.phone} onChange={(value) => update((draft) => { draft.profile.phone = value; })} /></div><Field label="Email" type="email" value={resume.profile.email} onChange={(value) => update((draft) => { draft.profile.email = value; })} /><TextArea label="Professional summary" value={resume.profile.summary} onChange={(value) => update((draft) => { draft.profile.summary = value; })} />
          <h3>Header links</h3>{resume.profile.links.map((link, index) => <div className="subcard" key={link.id}><div className="inline-actions"><strong>{link.label}</strong><IconButton label={`Remove ${link.label}`} onClick={() => update((draft) => { draft.profile.links.splice(index, 1); })}>Remove</IconButton></div><div className="field-grid"><Field label="Label" value={link.label} onChange={(value) => update((draft) => { draft.profile.links[index].label = value; })} /><label className="field"><span>Type</span><select value={link.kind} onChange={(event) => update((draft) => { draft.profile.links[index].kind = event.target.value as ContactLink["kind"]; })}>{["linkedin", "portfolio", "github", "email", "custom"].map((kind) => <option key={kind}>{kind}</option>)}</select></label></div><Field label="Visible text" value={link.displayText} onChange={(value) => update((draft) => { draft.profile.links[index].displayText = value; })} /><Field label="URL" value={link.url} onChange={(value) => update((draft) => { draft.profile.links[index].url = value; })} /></div>)}<button onClick={() => update((draft) => { draft.profile.links.push({ id: makeId(), kind: "custom", label: "Portfolio", displayText: "portfolio.example.com", url: "https://" }); })}>Add header link</button>
        </Panel>
        <Panel title="Experience">{resume.experience.map((role, roleIndex) => <div className="edit-card" key={role.id}><div className="card-title"><strong>{role.organization || "New experience"}</strong><div><IconButton label="Move experience up" disabled={!roleIndex} onClick={() => update((draft) => { draft.experience = move(draft.experience, roleIndex, roleIndex - 1); })}>↑</IconButton><IconButton label="Move experience down" disabled={roleIndex === resume.experience.length - 1} onClick={() => update((draft) => { draft.experience = move(draft.experience, roleIndex, roleIndex + 1); })}>↓</IconButton><IconButton label="Remove experience" onClick={() => { if (confirm("Remove this experience entry?")) update((draft) => { draft.experience.splice(roleIndex, 1); }); }}>Remove</IconButton></div></div><Field label="Organization" value={role.organization} onChange={(value) => update((draft) => { draft.experience[roleIndex].organization = value; })} /><div className="field-grid"><Field label="Title" value={role.title} onChange={(value) => update((draft) => { draft.experience[roleIndex].title = value; })} /><Field label="Location (optional)" value={role.location} onChange={(value) => update((draft) => { draft.experience[roleIndex].location = value; })} /></div><DateEditor value={role.date} onChange={(date) => update((draft) => { draft.experience[roleIndex].date = date; })} /><BulletEditor bullets={role.bullets} label="Experience bullets" onChange={(bullets) => update((draft) => { draft.experience[roleIndex].bullets = bullets; })} /></div>)}<button onClick={() => update((draft) => { draft.experience.push({ id: makeId(), organization: "", title: "", location: "", date: { startMonth: new Date().toISOString().slice(0, 7), current: true }, bullets: [] }); })}>Add experience</button></Panel>
        <Panel title="Projects"><p className="panel-help">Project titles link only when the catalog verifies a live deployment. Repository URLs and disclosures never print.</p><div className="project-picker">{projectCatalog.map((project) => <button key={project.slug} disabled={resume.projects.some((item) => item.catalogSlug === project.slug)} onClick={() => addProject(project.slug)}>+ {project.title}</button>)}</div>{resume.projects.map((project, projectIndex) => <div className="edit-card" key={project.id}><div className="card-title"><strong>{project.catalogSlug}</strong><div><IconButton label="Move project up" disabled={!projectIndex} onClick={() => update((draft) => { draft.projects = move(draft.projects, projectIndex, projectIndex - 1); })}>↑</IconButton><IconButton label="Move project down" disabled={projectIndex === resume.projects.length - 1} onClick={() => update((draft) => { draft.projects = move(draft.projects, projectIndex, projectIndex + 1); })}>↓</IconButton><IconButton label="Remove project" onClick={() => update((draft) => { draft.projects.splice(projectIndex, 1); })}>Remove</IconButton></div></div><Field label="Project title" value={project.title} onChange={(value) => update((draft) => { draft.projects[projectIndex].title = value; })} /><TechnologyEditor technologies={project.technologies} onChange={(technologies) => update((draft) => { draft.projects[projectIndex].technologies = technologies; })} /><BulletEditor bullets={project.bullets} label="Project bullets" onChange={(bullets) => update((draft) => { draft.projects[projectIndex].bullets = bullets; })} /><p className="verified-link">{getVerifiedProjectLiveUrl(project.catalogSlug) ? "Verified live link embedded in the project title." : "No verified live link; this project title stays plain text."}</p></div>)}</Panel>
        <Panel title="Skills">{resume.skillGroups.map((group, groupIndex) => <div className="edit-card" key={group.id}><div className="card-title"><strong>{group.label || "Skill group"}</strong><IconButton label="Remove skill group" onClick={() => update((draft) => { draft.skillGroups.splice(groupIndex, 1); })}>Remove</IconButton></div><Field label="Category" value={group.label} onChange={(value) => update((draft) => { draft.skillGroups[groupIndex].label = value; })} /><TechnologyEditor label="Skills" technologies={group.items} onChange={(items) => update((draft) => { draft.skillGroups[groupIndex].items = items; })} /></div>)}<button onClick={() => update((draft) => { draft.skillGroups.push({ id: makeId(), label: "New category", items: [] }); })}>Add skill category</button></Panel>
        <Panel title="Education & certifications">{resume.education.map((item, index) => <div className="edit-card" key={item.id}><div className="card-title"><strong>{item.institution || "Education"}</strong><IconButton label="Remove education" onClick={() => update((draft) => { draft.education.splice(index, 1); })}>Remove</IconButton></div><Field label="Institution" value={item.institution} onChange={(value) => update((draft) => { draft.education[index].institution = value; })} /><Field label="Degree" value={item.degree} onChange={(value) => update((draft) => { draft.education[index].degree = value; })} /><DateEditor value={item.date} onChange={(date) => update((draft) => { draft.education[index].date = date; })} /></div>)}<button onClick={() => update((draft) => { draft.education.push({ id: makeId(), institution: "", degree: "", date: { startMonth: new Date().toISOString().slice(0, 7), current: false } }); })}>Add education</button><h3>Certifications</h3>{resume.certifications.map((item, index) => <div className="edit-card" key={item.id}><div className="card-title"><strong>{item.label || "Certification"}</strong><IconButton label="Remove certification" onClick={() => update((draft) => { draft.certifications.splice(index, 1); })}>Remove</IconButton></div><Field label="Issuer" value={item.issuer} onChange={(value) => update((draft) => { draft.certifications[index].issuer = value; })} /><Field label="Certification" value={item.label} onChange={(value) => update((draft) => { draft.certifications[index].label = value; })} /><Field label="Note" value={item.note} onChange={(value) => update((draft) => { draft.certifications[index].note = value; })} /></div>)}<button onClick={() => update((draft) => { draft.certifications.push({ id: makeId(), issuer: "", label: "", note: "" }); })}>Add certification</button></Panel>
        <Panel title="Layout & appearance"><p className="panel-help">Safe presets keep body copy readable and preserve ATS-friendly structure.</p><label className="field"><span>Font</span><select value={resume.appearance.font} onChange={(event) => update((draft) => { draft.appearance.font = event.target.value as ResumeDocument["appearance"]["font"]; })}>{fontOptions.map((font) => <option key={font} value={font}>{font.replace(/-/g, " ")}</option>)}</select></label><div className="field-grid"><label className="field"><span>Accent</span><select value={resume.appearance.accent} onChange={(event) => update((draft) => { draft.appearance.accent = event.target.value as ResumeDocument["appearance"]["accent"]; })}>{accentOptions.map((accent) => <option key={accent}>{accent}</option>)}</select></label><label className="field"><span>Bullet style</span><select value={resume.appearance.bulletStyle} onChange={(event) => update((draft) => { draft.appearance.bulletStyle = event.target.value as ResumeDocument["appearance"]["bulletStyle"]; })}>{bulletStyles.map((style) => <option key={style}>{style}</option>)}</select></label></div><div className="field-grid"><label className="field"><span>Page size</span><select value={resume.page.size} onChange={(event) => update((draft) => { draft.page.size = event.target.value as "letter" | "a4"; })}><option value="letter">US Letter</option><option value="a4">A4</option></select></label><label className="field"><span>Fit behavior</span><select value={resume.page.fitMode} onChange={(event) => update((draft) => { draft.page.fitMode = event.target.value as ResumeDocument["page"]["fitMode"]; })}><option value="automatic">Automatic</option><option value="force-one-page">Force one page</option><option value="force-two-pages">Force two pages</option></select></label></div><label className="check-row"><input type="checkbox" checked={resume.appearance.contactIcons} onChange={(event) => update((draft) => { draft.appearance.contactIcons = event.target.checked; })} /> Show decorative contact icons with visible text</label><h3>Section order</h3>{resume.sectionOrder.map((section, index) => <div className="order-row" key={section}><span>{sectionLabels[section]}</span><IconButton label={`Move ${sectionLabels[section]} up`} disabled={!index} onClick={() => update((draft) => { draft.sectionOrder = move(draft.sectionOrder, index, index - 1); })}>↑</IconButton><IconButton label={`Move ${sectionLabels[section]} down`} disabled={index === resume.sectionOrder.length - 1} onClick={() => update((draft) => { draft.sectionOrder = move(draft.sectionOrder, index, index + 1); })}>↓</IconButton></div>)}</Panel>
      </aside>
      <section className="preview-stage" aria-label="Live printable preview"><div className="preview-meta no-print"><span>Live print preview</span><strong className={fit === "overflow" ? "warning" : ""}>{fitLabel}</strong></div><ResumePreview document={resume} fit={fit} onFitChange={setFit} /></section>
    </div>
  </main>;
}

function Panel({ title, children, open = false }: { title: string; children: ReactNode; open?: boolean }) { return <details className="editor-panel" open={open}><summary>{title}</summary><div className="panel-body">{children}</div></details>; }
function Field({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label className="field"><span>{label}</span><input type={type} value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
function TextArea({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="field"><span>{label}</span><textarea value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
function IconButton({ label, children, ...props }: { label: string; children: ReactNode } & React.ButtonHTMLAttributes<HTMLButtonElement>) { return <button className="icon-button" aria-label={label} title={label} {...props}>{children}</button>; }

function DateEditor({ value, onChange }: { value: DateRange; onChange: (value: DateRange) => void }) { return <div className="date-editor"><div className="field-grid"><label className="field"><span>Start date</span><input type="month" value={value.startMonth ?? ""} onChange={(event) => onChange({ ...value, startMonth: event.target.value || undefined, legacyDateText: undefined })} /></label><label className="field"><span>End date</span><input type="month" disabled={value.current} value={value.endMonth ?? ""} onChange={(event) => onChange({ ...value, endMonth: event.target.value || undefined, legacyDateText: undefined })} /></label></div><label className="check-row"><input type="checkbox" checked={value.current} onChange={(event) => onChange({ ...value, current: event.target.checked, endMonth: event.target.checked ? undefined : value.endMonth })} /> Current role / program</label>{value.legacyDateText && <p className="legacy-date">Imported date: {value.legacyDateText}</p>}</div>; }
function BulletEditor({ bullets, label, onChange }: { bullets: BulletItem[]; label: string; onChange: (bullets: BulletItem[]) => void }) { return <div className="bullet-editor"><h3>{label}</h3>{bullets.map((bullet, index) => <div className="bullet-row" key={bullet.id}><TextArea label={`Bullet ${index + 1}`} value={bullet.text} onChange={(text) => onChange(bullets.map((item) => item.id === bullet.id ? { ...item, text } : item))} /><div className="bullet-actions"><IconButton label="Move bullet up" disabled={!index} onClick={() => onChange(move(bullets, index, index - 1))}>↑</IconButton><IconButton label="Move bullet down" disabled={index === bullets.length - 1} onClick={() => onChange(move(bullets, index, index + 1))}>↓</IconButton><IconButton label="Duplicate bullet" onClick={() => onChange([...bullets.slice(0, index + 1), { id: makeId(), text: bullet.text }, ...bullets.slice(index + 1)])}>Duplicate</IconButton><IconButton label="Remove bullet" onClick={() => onChange(bullets.filter((item) => item.id !== bullet.id))}>Remove</IconButton></div></div>)}<button onClick={() => onChange([...bullets, { id: makeId(), text: "" }])}>Add bullet</button></div>; }
function TechnologyEditor({ technologies, onChange, label = "Technologies" }: { technologies: string[]; onChange: (items: string[]) => void; label?: string }) { const [entry, setEntry] = useState(""); const add = () => { const value = entry.trim(); if (!value || technologies.includes(value)) return; onChange([...technologies, value]); setEntry(""); }; return <div className="technology-editor"><span className="field-label">{label}</span><div className="chips">{technologies.map((technology, index) => <span className="chip" key={`${technology}-${index}`}>{technology}<button aria-label={`Remove ${technology}`} onClick={() => onChange(technologies.filter((_, itemIndex) => itemIndex !== index))}>×</button><button aria-label={`Move ${technology} earlier`} disabled={!index} onClick={() => onChange(move(technologies, index, index - 1))}>←</button><button aria-label={`Move ${technology} later`} disabled={index === technologies.length - 1} onClick={() => onChange(move(technologies, index, index + 1))}>→</button></span>)}</div><div className="tech-add"><input aria-label={`Add ${label.toLowerCase()}`} value={entry} placeholder="Add technology" onChange={(event) => setEntry(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") { event.preventDefault(); add(); } }} /><button onClick={add}>Add</button></div></div>; }

function ResumePreview({ document, fit, onFitChange }: { document: ResumeDocument; fit: Fit; onFitChange: (fit: Fit) => void }) {
  const pageRef = useRef<HTMLElement>(null);
  const requested = document.page.fitMode;
  useLayoutEffect(() => {
    const page = pageRef.current; if (!page) return;
    const measure = () => {
      const overflows = page.scrollHeight > page.clientHeight + 2;
      if (requested === "force-two-pages") return onFitChange("two-page");
      if (requested === "force-one-page") return onFitChange(overflows ? "overflow" : "compact");
      if (!overflows && fit !== "compact") return onFitChange("comfortable");
      if (overflows && fit === "comfortable") return onFitChange("compact");
      if (overflows && fit === "compact") return onFitChange("two-page");
    };
    const frame = requestAnimationFrame(measure); const observer = new ResizeObserver(measure); observer.observe(page); return () => { cancelAnimationFrame(frame); observer.disconnect(); };
  }, [document, fit, onFitChange, requested]);
  const className = `resume-page ${document.page.size} ${document.appearance.font} ${document.appearance.accent} bullet-${document.appearance.bulletStyle} fit-${fit}`;
  return <article ref={pageRef} className={className} aria-label="Printable resume preview"><header className="resume-header"><h1>{document.profile.name}</h1>{document.profile.headline && <p className="headline">{document.profile.headline}</p>}<p className="contact-line">{[document.profile.location, document.profile.phone, document.profile.email].filter(Boolean).map((item, index) => <span key={item}>{index > 0 && <b aria-hidden="true"> | </b>}{item}</span>)}{document.profile.links.map((link) => <span key={link.id}><b aria-hidden="true"> | </b>{document.appearance.contactIcons && <span aria-hidden="true" className="contact-icon">⌁</span>}<a href={link.url}>{link.displayText}</a></span>)}</p></header>{document.sectionOrder.map((section) => <PreviewSection key={section} section={section} document={document} />)}</article>;
}
function PreviewSection({ section, document }: { section: SectionKey; document: ResumeDocument }) {
  if (section === "certifications" && !document.certifications.length) return null;
  if (section === "projects" && !document.projects.length) return null;
  return <section className={`resume-section resume-${section}`}><h2>{sectionLabels[section]}</h2>{section === "summary" && <p>{document.profile.summary}</p>}{section === "experience" && document.experience.map((role) => <div className="resume-entry" key={role.id}><p className="resume-row"><span><strong>{role.organization}</strong>{role.title && <><b> | </b>{role.title}</>}</span><em>{formatDate(role.date)}</em></p>{role.location && <p className="entry-location">{role.location}</p>}<ul>{role.bullets.filter((bullet) => bullet.text).map((bullet) => <li key={bullet.id}>{bullet.text}</li>)}</ul></div>)}{section === "projects" && document.projects.map((project) => { const liveUrl = getVerifiedProjectLiveUrl(project.catalogSlug); return <div className="resume-entry resume-project" key={project.id}><p><strong>{liveUrl ? <a href={liveUrl}>{project.title}</a> : project.title}</strong>{project.technologies.length > 0 && <><b> | </b><em>{project.technologies.join(", ")}</em></>}</p><ul>{project.bullets.filter((bullet) => bullet.text).map((bullet) => <li key={bullet.id}>{bullet.text}</li>)}</ul></div>; })}{section === "skills" && document.skillGroups.filter((group) => group.label || group.items.length).map((group) => <p className="skill-line" key={group.id}><strong>{group.label}:</strong> {group.items.join(", ")}</p>)}{section === "education" && document.education.map((item) => <p className="resume-row education-row" key={item.id}><span><strong>{item.institution}</strong>{item.degree && <><b> | </b>{item.degree}</>}</span><em>{formatDate(item.date)}</em></p>)}{section === "certifications" && document.certifications.map((item) => <p key={item.id}><strong>{item.issuer}</strong>{item.issuer && item.label && <b> | </b>}{item.label} {item.note}</p>)}</section>;
}
